# Generated by Django 5.1.7 on 2025-04-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_cinema_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Thời lượng (phút)')),
                ('release_date', models.DateField()),
                ('poster_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.cinema')),
            ],
        ),
    ]
