# Generated by Django 5.1.7 on 2025-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_movie_actors_movie_country_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
